### ISSUE TITLE
Вопрос по parsedat.c

### ISSUE THREAD

**Issue by ank0l0g** [Shtirlitz/RZ09#1]
День добрый.
В README.md вы пишете
## parsedat.c
Анализирует японский файл данных AVIC-RZ09 (и аналогичные) initDB.dat.
Пропускает некоторые фиктивные строки (например, изображения, идентификаторы, переменные и т. Д.).
Записывает строки «как есть» с разделителем табуляции.
Поля: `<адрес>` `<длина>` `<исходная строка>`
Натравил parsedat на свой initDB.dat, получил parsed1.txt
Смотрю содержимое нового файла вижу следующее
00150798	0000000A	3989#	
001507A4	0000000A	3990#	
001507B0	00000008	FULL	
001507BC	0000000A	3991#	
001507C8	00000008	JUST	
001507D4	0000000A	3992#	
001507E0	0000000C	CINEMA	
001507F0	0000000A	3993#	
001507FC	00000008	ZOOM	
00150808	0000000A	3994#	
Думаю что же это за цифры 3989#, 3990# и т.д.
Смотрю initDB.dat вижу тоже самое.
Что сие может означать, стоит ли их учитывать ?

**Comment by easttimour** [comment]
@Shtirlitz

**Comment by alexk838** [comment]
@ank0l0g 
Это просто строчки, которые найдены в initDB.dat, часть из них я отбрасываю в коде (там ESC-последовательности, какие-то внутренние идентификаторы, имена файлов картинок и прочий мусор, не имеющий отношения к переводу).
Если интересно что там еще внутри есть - можно закомментить кусок if на 71й строке parsedat.c, и он вытащит вообще все строчки)
