### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by ZoraizQ** [Shtirlitz/RZ09#3]
How do I use this?

**Comment by ZoraizQ** [comment]
After the FW file is ready, what do I do?

**Comment by alexk838** [comment]
Hi!

Just use this step-by-step manual (2 posts): http://4pda.ru/forum/index.php?showtopic=847671&st=20#entry90149444

It's in Russian but I think it's easy to translate to English.

Good luck!

Alex

**Comment by Vinz320** [comment]
Sir, i followed ur instructions on #3 but when i run translate. C its not generating initdata.out. Please help

**Comment by alexk838** [comment]
> Sir, i followed ur instructions on #3 but when i run translate. C its not generating initdata.out. Please help

Please see the next post, it updates Step 4:
https://4pda.to/forum/index.php?showtopic=847671&view=findpost&p=90197725 
This command renames translated file to proper name.
copy /Y initDB_out.dat initDB.dat
